(define (problem problema1)
    	(:domain robot)
  	(:init (localizacion robot cocina)
		(localizacion libro salon)
		(localizacion mesa salon)
		(localizacion cafe salon)
	 	(localizacion fruta salon)
        (localizacion vaso salon)
		(robotLibre)
	)
  	(:goal (and (localizacion libro cocina) (localizacion mesa cocina) 
    (localizacion cafe cocina) (localizacion fruta cocina) (localizacion vaso cocina)
     (localizacion robot salon)))
;el robot se encuentra en la cocina; tiene que mover todos los objetos del salon a la cocina y debe acabar en el salón. con vpop me quedo sin ram y con SMTPLan no acaba el problema
) 